import test from 'node:test';
import assert from 'node:assert/strict';
import { processEmbeddingBatch, retryDelaySeconds } from '../src/corpus/embedding-worker.mjs';
import { UpstreamServiceError } from '../src/retrieval/supabase-retriever.mjs';
function job(overrides={}) { return { paperId:'p1', inputHash:'hash-1', model:'text-embedding-3-small', dimensions:512, attempts:1, title:'Paper', abstract:'A sufficiently descriptive abstract for a paper.', conferenceName:'ICA', conferenceYear:2026, division:'Political Communication', keywords:['AI'], ...overrides }; }
function storeWith(jobs, completeResult=true) { const calls={completed:[],released:[]}; return { calls, async claimEmbeddingJobs(){return jobs;}, async completeEmbeddingJob(v){calls.completed.push(v);return completeResult;}, async releaseEmbeddingJob(v){calls.released.push(v);return true;} }; }
test('worker completes a claimed batch with validated 512-dimensional vectors', async () => { const store=storeWith([job(),job({paperId:'p2',inputHash:'hash-2'})]); const embeddingClient={ async embedMany(texts,{dimensions}) { assert.equal(dimensions,512); assert.equal(texts.length,2); return texts.map(()=>Array(512).fill(0.1)); } }; const result=await processEmbeddingBatch({store,embeddingClient,batchSize:64}); assert.equal(result.claimed,2); assert.equal(result.completed,2); assert.equal(store.calls.completed.length,2); assert.equal(store.calls.released.length,0); });
test('transient provider errors release jobs for a bounded retry', async () => { const store=storeWith([job({attempts:2})]); const embeddingClient={ async embedMany(){ throw new UpstreamServiceError('OpenAI embeddings','rate limited',429); } }; const now=new Date('2026-08-22T10:00:00.000Z'); const result=await processEmbeddingBatch({store,embeddingClient,maxAttempts:5,now:()=>now}); assert.equal(result.retried,1); assert.equal(store.calls.released[0].terminal,false); assert.match(store.calls.released[0].errorCode,/rate_limited/); assert.equal(new Date(store.calls.released[0].nextAttemptAt).getTime(), now.getTime()+retryDelaySeconds(2)*1000); });
test('terminal provider errors fail the job without retry', async () => { const store=storeWith([job()]); const embeddingClient={ async embedMany(){ throw new UpstreamServiceError('OpenAI embeddings','bad request',400); } }; const result=await processEmbeddingBatch({store,embeddingClient}); assert.equal(result.failed,1); assert.equal(store.calls.released[0].terminal,true); });
test('worker rejects malformed embedding dimensions and does not complete a job', async () => { const store=storeWith([job()]); const embeddingClient={ async embedMany(){ return [[0.1,0.2]]; } }; const result=await processEmbeddingBatch({store,embeddingClient}); assert.equal(result.failed,1); assert.equal(store.calls.completed.length,0); assert.equal(store.calls.released[0].errorCode,'invalid_embedding_dimensions'); });
test('stale completion is counted without overwriting newer content', async () => { const store=storeWith([job()], false); const embeddingClient={ async embedMany(){ return [Array(512).fill(0.1)]; } }; const result=await processEmbeddingBatch({store,embeddingClient}); assert.equal(result.stale,1); assert.equal(result.completed,0); });
