const allowedOrigins=new Set(['https://mamingsuper.github.io','http://localhost:3000','http://localhost:4173','http://localhost:8080']);
function responseHeaders(req:Request,extra:HeadersInit={}){const origin=req.headers.get('origin');const headers=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-methods':'GET, OPTIONS','access-control-allow-headers':'authorization, content-type','vary':'Origin',...Object.fromEntries(new Headers(extra))});if(origin&&allowedOrigins.has(origin))headers.set('access-control-allow-origin',origin);return headers;}
const json=(data:unknown,status=200,req:Request,extra:HeadersInit={})=>new Response(JSON.stringify(data,null,2),{status,headers:responseHeaders(req,extra)});
export async function handleExportAccountRequest(req:Request,deps:any){
  const origin=req.headers.get('origin');if(origin&&!allowedOrigins.has(origin))return json({error:{code:'ORIGIN_NOT_ALLOWED',message:'Origin not allowed.'}},403,req);
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:responseHeaders(req)});
  if(req.method!=='GET')return json({error:{code:'METHOD_NOT_ALLOWED',message:'Use GET.'}},405,req,{allow:'GET, OPTIONS'});
  try{const token=req.headers.get('authorization')?.match(/^Bearer\s+([^\s]+)$/i)?.[1]??'';const user=await deps.authenticate(token);if(!user?.id)return json({error:{code:'AUTH_REQUIRED',message:'Sign in.'}},401,req);const data=await deps.export(user.id);return json({exportedAt:new Date().toISOString(),...data},200,req,{'content-disposition':'attachment; filename="idea-radar-account-export.json"'});}catch{return json({error:{code:'EXPORT_UNAVAILABLE',message:'Account export is temporarily unavailable.'}},503,req);}
}
const runtime=(globalThis as{Deno?:{serve?:Function;env?:{get(name:string):string|undefined}}}).Deno;
if(runtime?.serve)runtime.serve(async(req:Request)=>{const{createClient}=await import('npm:@supabase/supabase-js@2.112.3');const url=runtime.env?.get('SUPABASE_URL')??'',publicKey=runtime.env?.get('SUPABASE_PUBLISHABLE_KEY')||runtime.env?.get('SUPABASE_ANON_KEY')||'',secret=runtime.env?.get('SUPABASE_SECRET_KEY')||runtime.env?.get('SUPABASE_SERVICE_ROLE_KEY')||'',service=createClient(url,secret,{auth:{persistSession:false}});return handleExportAccountRequest(req,{async authenticate(token:string){const client=createClient(url,publicKey,{global:{headers:{Authorization:`Bearer ${token}`}}});const{data,error}=await client.auth.getUser(token);return error?null:data.user;},async export(userId:string){const [profile,saved,sessions,submissions]=await Promise.all([service.from('profiles').select('display_name,preferred_language,created_at,updated_at').eq('user_id',userId).maybeSingle(),service.from('saved_papers').select('paper_id,note,tags,created_at,updated_at').eq('user_id',userId),service.from('analysis_sessions').select('id,title,idea_text,report,language,corpus_snapshot,created_at,updated_at').eq('user_id',userId),service.from('program_submissions').select('id,conference_name,conference_acronym,conference_year,discipline,official_conference_url,program_url,file_name,status,review_reason,created_at,updated_at').eq('user_id',userId)]);for(const result of[profile,saved,sessions,submissions])if(result.error)throw result.error;const ids=(saved.data??[]).map((row:any)=>row.paper_id);let papers:any[]=[];if(ids.length){const result=await service.from('papers').select('id,title,abstract,authors,conference_name,conference_year,division,keywords,source_url').in('id',ids);if(result.error)throw result.error;papers=result.data??[];}const byId=new Map(papers.map((paper:any)=>[paper.id,paper]));return{profile:profile.data,savedPapers:(saved.data??[]).map((row:any)=>({...row,paper:byId.get(row.paper_id)??null,paper_id:undefined})),analysisSessions:sessions.data??[],submissions:submissions.data??[]};}});});
