const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
type Deps={authenticate(token:string):Promise<{id:string;role:string}|null>;confirm(token:string,id:string):Promise<Record<string,unknown>>};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
export async function handleConfirmProgramRequest(req:Request,deps:Deps){
  if(req.method!=='POST')return json({error:{code:'METHOD_NOT_ALLOWED',message:'Use POST.'}},405);
  try{const bearer=req.headers.get('authorization')?.match(/^Bearer\s+([^\s]+)$/i)?.[1]??'';const user=await deps.authenticate(bearer);if(!user?.id)return json({error:{code:'AUTH_REQUIRED',message:'Sign in.'}},401);if(user.role!=='admin')return json({error:{code:'ADMIN_REQUIRED',message:'Administrator access is required.'}},403);const body=await req.json();if(!body||Object.keys(body).some((key)=>key!=='submissionId')||!UUID.test(body.submissionId??''))return json({error:{code:'INVALID_REQUEST',message:'Invalid request.'}},400);return json({data:await deps.confirm(bearer,body.submissionId)});}catch{return json({error:{code:'CONFIRM_UNAVAILABLE',message:'The import could not be confirmed.'}},503);}
}
const runtime=(globalThis as {Deno?:{serve?:Function;env?:{get(name:string):string|undefined}}}).Deno;
if(runtime?.serve)runtime.serve(async(req:Request)=>{const{createClient}=await import('npm:@supabase/supabase-js@2.112.3');const url=runtime.env?.get('SUPABASE_URL')??'',key=runtime.env?.get('SUPABASE_PUBLISHABLE_KEY')||runtime.env?.get('SUPABASE_ANON_KEY')||'';const client=(token:string)=>createClient(url,key,{auth:{persistSession:false},global:{headers:{Authorization:`Bearer ${token}`}}});return handleConfirmProgramRequest(req,{async authenticate(token){const{data,error}=await client(token).auth.getUser(token);return error||!data.user?null:{id:data.user.id,role:data.user.app_metadata?.role==='admin'?'admin':''};},async confirm(token,id){const{data,error}=await client(token).rpc('confirm_program_import',{submission_id:id});if(error)throw error;return data;}});});
