function issuedAt(token:string){try{return Number(JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).iat);}catch{return 0;}}
const allowedOrigins=new Set(['https://mamingsuper.github.io','http://localhost:3000','http://localhost:4173','http://localhost:8080','http://localhost:8443','http://127.0.0.1:8443']);
function responseHeaders(req:Request,extra:HeadersInit={}){const origin=req.headers.get('origin');const headers=new Headers({'cache-control':'no-store','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'authorization, content-type','vary':'Origin',...Object.fromEntries(new Headers(extra))});if(origin&&allowedOrigins.has(origin))headers.set('access-control-allow-origin',origin);return headers;}
export async function handleDeleteAccountRequest(req:Request,deps:any){
  const origin=req.headers.get('origin');const headers=responseHeaders(req);if(origin&&!allowedOrigins.has(origin))return new Response(null,{status:403,headers});if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return new Response(null,{status:405,headers:responseHeaders(req,{allow:'POST, OPTIONS'})});
  try{const token=req.headers.get('authorization')?.match(/^Bearer\s+([^\s]+)$/i)?.[1]??'';const user=await deps.authenticate(token);if(!user?.id)return new Response(null,{status:401,headers});if(Math.floor(Date.now()/1000)-issuedAt(token)>600)return new Response(JSON.stringify({error:{code:'REAUTH_REQUIRED',message:'Sign in again before deleting your account.'}}),{status:401,headers:responseHeaders(req,{'content-type':'application/json'})});const body=await req.json();if(body?.confirmation!=='DELETE MY ACCOUNT'||Object.keys(body).some((key)=>key!=='confirmation'))return new Response(null,{status:400,headers});const cleanup=await deps.cleanup(user.id);await deps.removeStorage(cleanup.storagePaths??[]);await deps.deleteUser(user.id);return new Response(null,{status:204,headers});}catch{return new Response(JSON.stringify({error:{code:'DELETE_UNAVAILABLE',message:'Account deletion could not be completed.'}}),{status:503,headers:responseHeaders(req,{'content-type':'application/json'})});}
}
const runtime=(globalThis as{Deno?:{serve?:Function;env?:{get(name:string):string|undefined}}}).Deno;
if(runtime?.serve)runtime.serve(async(req:Request)=>{const{createClient}=await import('npm:@supabase/supabase-js@2.112.3');const url=runtime.env?.get('SUPABASE_URL')??'',publicKey=runtime.env?.get('SUPABASE_PUBLISHABLE_KEY')||runtime.env?.get('SUPABASE_ANON_KEY')||'',secret=runtime.env?.get('SUPABASE_SECRET_KEY')||runtime.env?.get('SUPABASE_SERVICE_ROLE_KEY')||'',service=createClient(url,secret,{auth:{persistSession:false}});return handleDeleteAccountRequest(req,{async authenticate(token:string){const client=createClient(url,publicKey,{global:{headers:{Authorization:`Bearer ${token}`}}});const{data,error}=await client.auth.getUser(token);return error?null:data.user;},async cleanup(id:string){const{data,error}=await service.rpc('delete_user_workspace',{target_user_id:id});if(error)throw error;return data;},async removeStorage(paths:string[]){if(paths.length){const{error}=await service.storage.from('program-submissions').remove(paths);if(error)throw error;}},async deleteUser(id:string){const{error}=await service.auth.admin.deleteUser(id);if(error)throw error;}});});
